name: Build and Test DOME WAR file 
# This workflow is triggered on pushes to the repository.
on: [pull_request]

jobs:
  build:
    # Job name is Greeting
    name: Build DOME WAR File
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      #- name: Hello world
      #  uses: actions/hello-world-javascript-action@v1
      #  with:
      #    who-to-greet: 'Mona the Octocat'
      #  id: hello
      # This step prints an output (time) from the previous step's action.
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Build
        run: ant compile-all-dome
      - name: Build
        run: ant build-test
      - name: Test
        run: ant test
      - name: Package WAR file
        run: ant dist-war
#      - name: Upload DOMEApiServicesV7 WAR
#        uses: actions/upload-artifact@v1
#        with:
#          name: DOMEApiServicesV7.war
#          path: dist/war/DOMEApiServicesV7.war


      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: beckmann/dome
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


# need to add docker
#- name: Docker Build
#        run: ./1-built.sh
