name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Build DOME WAR File
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      #- name: Hello world
      #  uses: actions/hello-world-javascript-action@v1
      #  with:
      #    who-to-greet: 'Mona the Octocat'
      #  id: hello
      # This step prints an output (time) from the previous step's action.
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Build WAR file
        run: ant build
      - name: Build WAR file
        run: ant build-test
      - name: Build WAR file
        run: ant test
      - name: Build WAR file
        run: ant dist-war
      - name: list
        run: ls
      - name: Upload DOMEApiServicesV7 WAR
        uses: actions/upload-artifact@v1
        with:
          name: DOMEApiServicesV7.war
          path: dist/war/DOMEApiServicesV7.war